import = ["~/.config/alacritty/dark_plus.toml"]

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
size = 10

[window]
padding = { x = 8, y = 8 }
